### ISSUE TITLE
Criar uma tela cadastrar

### ISSUE THREAD

**Issue by nicolastrres** [EVDPE/organizaMe#2]
Como o pai de Tullius
eu quero uma tela para poder cadastrar os filmes e as trilhas sonoras
para poder ler depois a informação e reproduzir a musica.

Criterio de aceitação:
Dado que entro na tela para cadastrar um filme
quando a tela abre 
então deve ter os seguintes campos: 
Titulo, Pais de origem, Diretor, Gênero, Tempo de duração, Ano de lanzamento, Idioma, Sinopsis, trilhas sonoras, link do trailer.

Dado que executo o programa e entro na tela,
quando preencho todos os campos
e clico salvar,
então os dados são salvos no banco de dados
e é mostrado uma messagem "Filme salvado"

Dado que executo o programa e entro na tela cadastrar,
quando preencho todos os campos 
e clico cancelar,
então a tela é fechada e aparece a tela anterior.

**Comment by tulliusvinicius** [comment]
Também foram criadas as seguintes restrições:

Os campos "Ano de lançamento" e "Duração" só aceitam números.

Os demais campos só aceitam letras.

**Comment by nicolastrres** [comment]
Ou seja que em sinopses não posso colocar numeros?

**Comment by tulliusvinicius** [comment]
Esqueci de por ai na descrição, porque sinopses poderão sim, pois há sinopses que faz referencias a anos, ou outras coisas com números.
